subroutine SwashCleanMem
!
!   --|-----------------------------------------------------------|--
!     | Delft University of Technology                            |
!     | Faculty of Civil Engineering                              |
!     | Environmental Fluid Mechanics Section                     |
!     | P.O. Box 5048, 2600 GA  Delft, The Netherlands            |
!     |                                                           |
!     | Programmers: The SWASH team                               |
!   --|-----------------------------------------------------------|--
!
!
!     SWASH (Simulating WAves till SHore); a non-hydrostatic wave-flow model
!     Copyright (C) 2010-2019  Delft University of Technology
!
!     This program is free software; you can redistribute it and/or
!     modify it under the terms of the GNU General Public License as
!     published by the Free Software Foundation; either version 2 of
!     the License, or (at your option) any later version.
!
!     This program is distributed in the hope that it will be useful,
!     but WITHOUT ANY WARRANTY; without even the implied warranty of
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
!     GNU General Public License for more details.
!
!     A copy of the GNU General Public License is available at
!     http://www.gnu.org/copyleft/gpl.html#SEC3
!     or by writing to the Free Software Foundation, Inc.,
!     59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
!
!
!   Authors
!
!    1.00: Marcel Zijlema
!
!   Updates
!
!    1.00, December 2009: New subroutine
!
!   Purpose
!
!   Cleans memory
!
!   Modules used
!
    use m_genarr
    use m_bndspec
    use outp_data
    use m_parall
    use SwanGriddata
    use SwanCompdata
    use SwashFlowdata
    use SwashSolvedata
!
    implicit none
!
!   Structure
!
!   Description of the pseudo code
!
!   Source text
!
    if ( allocated(bgridp) )  deallocate(bgridp)
    if ( allocated(kgrpnt) )  deallocate(kgrpnt)
    if ( allocated(xytst ) )  deallocate(xytst )
    if ( allocated(xcgrid) )  deallocate(xcgrid)
    if ( allocated(ycgrid) )  deallocate(ycgrid)
    if ( allocated(guu   ) )  deallocate(guu   )
    if ( allocated(guv   ) )  deallocate(guv   )
    if ( allocated(gvu   ) )  deallocate(gvu   )
    if ( allocated(gvv   ) )  deallocate(gvv   )
    if ( allocated(gsqs  ) )  deallocate(gsqs  )
    if ( allocated(gsqsu ) )  deallocate(gsqsu )
    if ( allocated(gsqsv ) )  deallocate(gsqsv )
    if ( allocated(indlay) )  deallocate(indlay)
    if ( allocated(hlay  ) )  deallocate(hlay  )
    if ( allocated(hlaysh) )  deallocate(hlaysh)
    if ( allocated(bndval) )  deallocate(bndval)
    if ( allocated(depth ) )  deallocate(depth )
    if ( allocated(wlevl ) )  deallocate(wlevl )
    if ( allocated(flobj ) )  deallocate(flobj )
    if ( allocated(fric  ) )  deallocate(fric  )
    if ( allocated(uxb   ) )  deallocate(uxb   )
    if ( allocated(uyb   ) )  deallocate(uyb   )
    if ( allocated(wxi   ) )  deallocate(wxi   )
    if ( allocated(wyi   ) )  deallocate(wyi   )
    if ( allocated(pres  ) )  deallocate(pres  )
    if ( allocated(npor  ) )  deallocate(npor  )
    if ( allocated(gsiz  ) )  deallocate(gsiz  )
    if ( allocated(hpor  ) )  deallocate(hpor  )
    if ( allocated(sal   ) )  deallocate(sal   )
    if ( allocated(temp  ) )  deallocate(temp  )
    if ( allocated(sed   ) )  deallocate(sed   )
    if ( allocated(npla  ) )  deallocate(npla  )
    if ( allocated(depf  ) )  deallocate(depf  )
    if ( allocated(wlevf ) )  deallocate(wlevf )
    if ( allocated(flobjf) )  deallocate(flobjf)
    if ( allocated(fricf ) )  deallocate(fricf )
    if ( allocated(uxf   ) )  deallocate(uxf   )
    if ( allocated(uyf   ) )  deallocate(uyf   )
    if ( allocated(wxf   ) )  deallocate(wxf   )
    if ( allocated(wyf   ) )  deallocate(wyf   )
    if ( allocated(presf ) )  deallocate(presf )
    if ( allocated(nporf ) )  deallocate(nporf )
    if ( allocated(gsizf ) )  deallocate(gsizf )
    if ( allocated(hporf ) )  deallocate(hporf )
    if ( allocated(salf  ) )  deallocate(salf  )
    if ( allocated(tempf ) )  deallocate(tempf )
    if ( allocated(sedf  ) )  deallocate(sedf  )
    if ( allocated(nplaf ) )  deallocate(nplaf )
    if ( allocated(hlayv ) )  deallocate(hlayv )
    if ( allocated(cdveg ) )  deallocate(cdveg )
    if ( allocated(bveg  ) )  deallocate(bveg  )
    if ( allocated(nveg  ) )  deallocate(nveg  )
    if ( allocated(s0    ) )  deallocate(s0    )
    if ( allocated(u0    ) )  deallocate(u0    )
    if ( allocated(u0p   ) )  deallocate(u0p   )
    if ( allocated(v0    ) )  deallocate(v0    )
    if ( allocated(v0p   ) )  deallocate(v0p   )
    if ( allocated(w0bot ) )  deallocate(w0bot )
    if ( allocated(w0top ) )  deallocate(w0top )
    if ( allocated(w0    ) )  deallocate(w0    )
    if ( allocated(w0p   ) )  deallocate(w0p   )
    if ( allocated(s1    ) )  deallocate(s1    )
    if ( allocated(u1    ) )  deallocate(u1    )
    if ( allocated(u1p   ) )  deallocate(u1p   )
    if ( allocated(v1    ) )  deallocate(v1    )
    if ( allocated(v1p   ) )  deallocate(v1p   )
    if ( allocated(w1bot ) )  deallocate(w1bot )
    if ( allocated(w1top ) )  deallocate(w1top )
    if ( allocated(w1    ) )  deallocate(w1    )
    if ( allocated(w1p   ) )  deallocate(w1p   )
    if ( allocated(udep  ) )  deallocate(udep  )
    if ( allocated(vdep  ) )  deallocate(vdep  )
    if ( allocated(wom   ) )  deallocate(wom   )
    if ( allocated(womp  ) )  deallocate(womp  )
    if ( allocated(dps   ) )  deallocate(dps   )
    if ( allocated(dpu   ) )  deallocate(dpu   )
    if ( allocated(dpv   ) )  deallocate(dpv   )
    if ( allocated(hs    ) )  deallocate(hs    )
    if ( allocated(hso   ) )  deallocate(hso   )
    if ( allocated(hu    ) )  deallocate(hu    )
    if ( allocated(hum   ) )  deallocate(hum   )
    if ( allocated(humn  ) )  deallocate(humn  )
    if ( allocated(humo  ) )  deallocate(humo  )
    if ( allocated(hv    ) )  deallocate(hv    )
    if ( allocated(hvm   ) )  deallocate(hvm   )
    if ( allocated(hvmn  ) )  deallocate(hvmn  )
    if ( allocated(hvmo  ) )  deallocate(hvmo  )
    if ( allocated(zks   ) )  deallocate(zks   )
    if ( allocated(zksnew) )  deallocate(zksnew)
    if ( allocated(zkso  ) )  deallocate(zkso  )
    if ( allocated(zku   ) )  deallocate(zku   )
    if ( allocated(zkum  ) )  deallocate(zkum  )
    if ( allocated(zkv   ) )  deallocate(zkv   )
    if ( allocated(zkvm  ) )  deallocate(zkvm  )
    if ( allocated(hks   ) )  deallocate(hks   )
    if ( allocated(hksc  ) )  deallocate(hksc  )
    if ( allocated(hksnew) )  deallocate(hksnew)
    if ( allocated(hkso  ) )  deallocate(hkso  )
    if ( allocated(hku   ) )  deallocate(hku   )
    if ( allocated(hkuc  ) )  deallocate(hkuc  )
    if ( allocated(hkum  ) )  deallocate(hkum  )
    if ( allocated(hkumc ) )  deallocate(hkumc )
    if ( allocated(hkumn ) )  deallocate(hkumn )
    if ( allocated(hkv   ) )  deallocate(hkv   )
    if ( allocated(hkvc  ) )  deallocate(hkvc  )
    if ( allocated(hkvm  ) )  deallocate(hkvm  )
    if ( allocated(hkvmc ) )  deallocate(hkvmc )
    if ( allocated(hkvmn ) )  deallocate(hkvmn )
    if ( allocated(hindun) )  deallocate(hindun)
    if ( allocated(hpors ) )  deallocate(hpors )
    if ( allocated(hporu ) )  deallocate(hporu )
    if ( allocated(hporv ) )  deallocate(hporv )
    if ( allocated(apoks ) )  deallocate(apoks )
    if ( allocated(apomu ) )  deallocate(apomu )
    if ( allocated(apomv ) )  deallocate(apomv )
    if ( allocated(apors ) )  deallocate(apors )
    if ( allocated(aporu ) )  deallocate(aporu )
    if ( allocated(aporv ) )  deallocate(aporv )
    if ( allocated(bpoks ) )  deallocate(bpoks )
    if ( allocated(bpomu ) )  deallocate(bpomu )
    if ( allocated(bpomv ) )  deallocate(bpomv )
    if ( allocated(bpors ) )  deallocate(bpors )
    if ( allocated(bporu ) )  deallocate(bporu )
    if ( allocated(bporv ) )  deallocate(bporv )
    if ( allocated(cpoks ) )  deallocate(cpoks )
    if ( allocated(cpomu ) )  deallocate(cpomu )
    if ( allocated(cpomv ) )  deallocate(cpomv )
    if ( allocated(cpors ) )  deallocate(cpors )
    if ( allocated(cporu ) )  deallocate(cporu )
    if ( allocated(cporv ) )  deallocate(cporv )
    if ( allocated(cfricu) )  deallocate(cfricu)
    if ( allocated(cfricv) )  deallocate(cfricv)
    if ( allocated(logfrc) )  deallocate(logfrc)
    if ( allocated(npoks ) )  deallocate(npoks )
    if ( allocated(npors ) )  deallocate(npors )
    if ( allocated(nporu ) )  deallocate(nporu )
    if ( allocated(nporv ) )  deallocate(nporv )
    if ( allocated(windu ) )  deallocate(windu )
    if ( allocated(windv ) )  deallocate(windv )
    if ( allocated(cwndu ) )  deallocate(cwndu )
    if ( allocated(cwndv ) )  deallocate(cwndv )
    if ( allocated(wndimp) )  deallocate(wndimp)
    if ( allocated(smax  ) )  deallocate(smax  )
    if ( allocated(so    ) )  deallocate(so    )
    if ( allocated(cbot  ) )  deallocate(cbot  )
    if ( allocated(cvegu ) )  deallocate(cvegu )
    if ( allocated(cvegv ) )  deallocate(cvegv )
    if ( allocated(flos  ) )  deallocate(flos  )
    if ( allocated(flou  ) )  deallocate(flou  )
    if ( allocated(flov  ) )  deallocate(flov  )
    if ( allocated(fcor  ) )  deallocate(fcor  )
    if ( allocated(patm  ) )  deallocate(patm  )
    if ( allocated(rho   ) )  deallocate(rho   )
    if ( allocated(ibl   ) )  deallocate(ibl   )
    if ( allocated(ibr   ) )  deallocate(ibr   )
    if ( allocated(ibb   ) )  deallocate(ibb   )
    if ( allocated(ibt   ) )  deallocate(ibt   )
    if ( allocated(wets  ) )  deallocate(wets  )
    if ( allocated(wetu  ) )  deallocate(wetu  )
    if ( allocated(wetv  ) )  deallocate(wetv  )
    if ( allocated(brks  ) )  deallocate(brks  )
    if ( allocated(presp ) )  deallocate(presp )
    if ( allocated(presu ) )  deallocate(presu )
    if ( allocated(presv ) )  deallocate(presv )
    if ( allocated(qx    ) )  deallocate(qx    )
    if ( allocated(qy    ) )  deallocate(qy    )
    if ( allocated(qm    ) )  deallocate(qm    )
    if ( allocated(qxm   ) )  deallocate(qxm   )
    if ( allocated(qym   ) )  deallocate(qym   )
    if ( allocated(advec ) )  deallocate(advec )
    if ( allocated(advecx) )  deallocate(advecx)
    if ( allocated(advecy) )  deallocate(advecy)
    if ( allocated(ua    ) )  deallocate(ua    )
    if ( allocated(ua2   ) )  deallocate(ua2   )
    if ( allocated(up    ) )  deallocate(up    )
    if ( allocated(ui    ) )  deallocate(ui    )
    if ( allocated(vi    ) )  deallocate(vi    )
    if ( allocated(teta  ) )  deallocate(teta  )
    if ( allocated(teta2 ) )  deallocate(teta2 )
    if ( allocated(tetau ) )  deallocate(tetau )
    if ( allocated(tetav ) )  deallocate(tetav )
    if ( allocated(dqgrd ) )  deallocate(dqgrd )
    if ( allocated(dqgrdu) )  deallocate(dqgrdu)
    if ( allocated(dqgrdv) )  deallocate(dqgrdv)
    if ( allocated(rp    ) )  deallocate(rp    )
    if ( allocated(rpo   ) )  deallocate(rpo   )
    if ( allocated(flux  ) )  deallocate(flux  )
    if ( allocated(cbndl ) )  deallocate(cbndl )
    if ( allocated(cbndr ) )  deallocate(cbndr )
    if ( allocated(cbndb ) )  deallocate(cbndb )
    if ( allocated(cbndt ) )  deallocate(cbndt )
    if ( allocated(coutl ) )  deallocate(coutl )
    if ( allocated(coutr ) )  deallocate(coutr )
    if ( allocated(coutb ) )  deallocate(coutb )
    if ( allocated(coutt ) )  deallocate(coutt )
    if ( allocated(icretl) )  deallocate(icretl)
    if ( allocated(icretr) )  deallocate(icretr)
    if ( allocated(icretb) )  deallocate(icretb)
    if ( allocated(icrett) )  deallocate(icrett)
    if ( allocated(visc  ) )  deallocate(visc  )
    if ( allocated(vnu2d ) )  deallocate(vnu2d )
    if ( allocated(vnu3d ) )  deallocate(vnu3d )
    if ( allocated(rtur  ) )  deallocate(rtur  )
    if ( allocated(zshear) )  deallocate(zshear)
    if ( allocated(rsuu  ) )  deallocate(rsuu  )
    if ( allocated(rsuv  ) )  deallocate(rsuv  )
    if ( allocated(rsuw  ) )  deallocate(rsuw  )
    if ( allocated(rsvu  ) )  deallocate(rsvu  )
    if ( allocated(rsvv  ) )  deallocate(rsvv  )
    if ( allocated(rsvw  ) )  deallocate(rsvw  )
    if ( allocated(rswu  ) )  deallocate(rswu  )
    if ( allocated(rswv  ) )  deallocate(rswv  )
    if ( allocated(rsww  ) )  deallocate(rsww  )
    if ( allocated(logwll) )  deallocate(logwll)
    if ( allocated(logwlr) )  deallocate(logwlr)
    if ( allocated(logwlb) )  deallocate(logwlb)
    if ( allocated(logwlt) )  deallocate(logwlt)
    if ( allocated(sponxl) )  deallocate(sponxl)
    if ( allocated(sponxr) )  deallocate(sponxr)
    if ( allocated(sponyb) )  deallocate(sponyb)
    if ( allocated(sponyt) )  deallocate(sponyt)
    if ( allocated(srcm  ) )  deallocate(srcm  )
    if ( allocated(tbndx ) )  deallocate(tbndx )
    if ( allocated(tbndy ) )  deallocate(tbndy )
    if ( allocated(uwetp ) )  deallocate(uwetp )
    if ( allocated(vwetp ) )  deallocate(vwetp )
    if ( allocated(slimp ) )  deallocate(slimp )
    if ( allocated(srimp ) )  deallocate(srimp )
    if ( allocated(sbimp ) )  deallocate(sbimp )
    if ( allocated(stimp ) )  deallocate(stimp )
    if ( allocated(msta  ) )  deallocate(msta  )
    if ( allocated(mend  ) )  deallocate(mend  )
    if ( allocated(nsta  ) )  deallocate(nsta  )
    if ( allocated(nend  ) )  deallocate(nend  )
    if ( allocated(npu   ) )  deallocate(npu   )
    if ( allocated(kup   ) )  deallocate(kup   )
    !
    if ( allocated(ds    ) )  deallocate(ds    )
    if ( allocated(q     ) )  deallocate(q     )
    if ( allocated(qv    ) )  deallocate(qv    )
    if ( allocated(dq    ) )  deallocate(dq    )
    if ( allocated(dqv   ) )  deallocate(dqv   )
    if ( allocated(gmatu ) )  deallocate(gmatu )
    if ( allocated(gmatv ) )  deallocate(gmatv )
    if ( allocated(gmatw ) )  deallocate(gmatw )
    if ( allocated(dmat  ) )  deallocate(dmat  )
    if ( allocated(pgrad ) )  deallocate(pgrad )
    if ( allocated(qgrad ) )  deallocate(qgrad )
    if ( allocated(qbot  ) )  deallocate(qbot  )
    if ( allocated(dq0   ) )  deallocate(dq0   )
    if ( allocated(gmatu0) )  deallocate(gmatu0)
    if ( allocated(gmatv0) )  deallocate(gmatv0)
    if ( allocated(gmatuv) )  deallocate(gmatuv)
    if ( allocated(gmatvv) )  deallocate(gmatvv)
    !
    if ( allocated(a     ) )  deallocate(a     )
    if ( allocated(an    ) )  deallocate(an    )
    if ( allocated(b     ) )  deallocate(b     )
    if ( allocated(ba    ) )  deallocate(ba    )
    if ( allocated(bn    ) )  deallocate(bn    )
    if ( allocated(c     ) )  deallocate(c     )
    if ( allocated(cn    ) )  deallocate(cn    )
    if ( allocated(d     ) )  deallocate(d     )
    if ( allocated(da    ) )  deallocate(da    )
    if ( allocated(dn    ) )  deallocate(dn    )
    if ( allocated(amat  ) )  deallocate(amat  )
    if ( allocated(amata ) )  deallocate(amata )
    if ( allocated(amatn ) )  deallocate(amatn )
    if ( allocated(rhs   ) )  deallocate(rhs   )
    if ( allocated(rhsa  ) )  deallocate(rhsa  )
    if ( allocated(rhsn  ) )  deallocate(rhsn  )
    if ( allocated(lon   ) )  deallocate(lon   )
    if ( allocated(upn   ) )  deallocate(upn   )
    if ( allocated(cmat  ) )  deallocate(cmat  )
    if ( allocated(resd  ) )  deallocate(resd  )
    if ( allocated(diag  ) )  deallocate(diag  )
    if ( allocated(s     ) )  deallocate(s     )
    if ( allocated(r     ) )  deallocate(r     )
    if ( allocated(z     ) )  deallocate(z     )
    if ( allocated(resd2 ) )  deallocate(resd2 )
    if ( allocated(diag2 ) )  deallocate(diag2 )
    if ( allocated(s2    ) )  deallocate(s2    )
    if ( allocated(r2    ) )  deallocate(r2    )
    if ( allocated(z3    ) )  deallocate(z3    )
    if ( allocated(prec  ) )  deallocate(prec  )
    if ( allocated(diagb ) )  deallocate(diagb )
    if ( allocated(res   ) )  deallocate(res   )
    if ( allocated(res0  ) )  deallocate(res0  )
    if ( allocated(p     ) )  deallocate(p     )
    if ( allocated(v     ) )  deallocate(v     )
    if ( allocated(w     ) )  deallocate(w     )
    if ( allocated(u     ) )  deallocate(u     )
    if ( allocated(sol   ) )  deallocate(sol   )
    if ( allocated(t     ) )  deallocate(t     )
    if ( allocated(vt    ) )  deallocate(vt    )
    if ( allocated(vt2   ) )  deallocate(vt2   )
    if ( allocated(z1    ) )  deallocate(z1    )
    if ( allocated(z2    ) )  deallocate(z2    )
    if ( allocated(z12   ) )  deallocate(z12   )
    if ( allocated(z22   ) )  deallocate(z22   )
    if ( allocated(p0    ) )  deallocate(p0    )
    if ( allocated(p1    ) )  deallocate(p1    )
    if ( allocated(q0    ) )  deallocate(q0    )
    if ( allocated(q1    ) )  deallocate(q1    )
    if ( allocated(amatu ) )  deallocate(amatu )
    if ( allocated(rhsu  ) )  deallocate(rhsu  )
    if ( allocated(amatw ) )  deallocate(amatw )
    if ( allocated(rhsw  ) )  deallocate(rhsw  )
    if ( allocated(amatp ) )  deallocate(amatp )
    if ( allocated(rhsp  ) )  deallocate(rhsp  )
    if ( allocated(amatc ) )  deallocate(amatc )
    if ( allocated(rhsc  ) )  deallocate(rhsc  )
    if ( allocated(amatt ) )  deallocate(amatt )
    if ( allocated(rhst  ) )  deallocate(rhst  )
    if ( allocated(ishif ) )  deallocate(ishif )
    !
    if ( allocated(iwrk  ) )  deallocate(iwrk  )
    if ( allocated(work  ) )  deallocate(work  )
    if ( allocated(wrk   ) )  deallocate(wrk   )
    if ( allocated(wphy  ) )  deallocate(wphy  )
    if ( allocated(oparr ) )  deallocate(oparr )
    if ( allocated(oparrk) )  deallocate(oparrk)
    if ( allocated(seed  ) )  deallocate(seed  )
    !
    if ( allocated(setup ) )  deallocate(setup )
    if ( allocated(etavar) )  deallocate(etavar)
    if ( allocated(hsig  ) )  deallocate(hsig  )
    if ( allocated(mvelu ) )  deallocate(mvelu )
    if ( allocated(mvelv ) )  deallocate(mvelv )
    if ( allocated(mcons ) )  deallocate(mcons )
    if ( allocated(mtke  ) )  deallocate(mtke  )
    if ( allocated(meps  ) )  deallocate(meps  )
    !
    if ( allocated(IBLKAD) )  deallocate(IBLKAD)
    if ( allocated(JHALOE) )  deallocate(JHALOE)
    if ( allocated(JHALOS) )  deallocate(JHALOS)
    if ( allocated(IWRKEX) )  deallocate(IWRKEX)
    if ( allocated(WRKEXG) )  deallocate(WRKEXG)
    if ( allocated(DWRKEX) )  deallocate(DWRKEX)
    if ( allocated(XGRDGL) )  deallocate(XGRDGL)
    if ( allocated(YGRDGL) )  deallocate(YGRDGL)
    if ( allocated(KGRPGL) )  deallocate(KGRPGL)
    !
    if ( allocated(xcugrd) )  deallocate(xcugrd)
    if ( allocated(ycugrd) )  deallocate(ycugrd)
    if ( allocated( vmark) )  deallocate( vmark)
    if ( allocated( vlist) )  deallocate( vlist)
    if ( allocated( blist) )  deallocate( blist)
    !
end subroutine SwashCleanMem
